import React from 'react';
import { Sparkles, ShieldCheck, Database, FileText, Users, HardHat } from 'lucide-react';

export type ProvenanceType =
  | 'AI_ANALYSIS'
  | 'OFFICIAL_DECISION'
  | 'GOVERNMENT_DATA'
  | 'PROTOTYPE_DATA'
  | 'COMMUNITY_VERIFICATION'
  | 'CONTRACTOR_SUBMISSION';

interface ProvenanceBadgeProps {
  type: ProvenanceType;
  modelOrSource?: string;
  className?: string;
  size?: 'sm' | 'md';
}

export const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({
  type,
  modelOrSource,
  className = '',
  size = 'sm',
}) => {
  const isSm = size === 'sm';

  switch (type) {
    case 'AI_ANALYSIS':
      return (
        <span
          className={`inline-flex items-center gap-1.5 font-medium rounded-full border border-purple-200 bg-purple-50 text-purple-800 ${
            isSm ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-sm'
          } ${className}`}
          title="Generated by AI model. Assistive only — Humans govern all consequential decisions."
        >
          <Sparkles className={`${isSm ? 'w-3 h-3' : 'w-4 h-4'} text-purple-600 animate-pulse`} />
          <span className="font-semibold">AI Analysis</span>
          {modelOrSource && <span className="text-purple-600/75 text-[10px]">({modelOrSource})</span>}
        </span>
      );

    case 'OFFICIAL_DECISION':
      return (
        <span
          className={`inline-flex items-center gap-1.5 font-medium rounded-full border border-emerald-300 bg-emerald-50 text-emerald-900 ${
            isSm ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-sm'
          } ${className}`}
          title="Certified Human Official Decision with legal governance authority."
        >
          <ShieldCheck className={`${isSm ? 'w-3 h-3' : 'w-4 h-4'} text-emerald-700`} />
          <span className="font-semibold">Official Human Decision</span>
        </span>
      );

    case 'GOVERNMENT_DATA':
      return (
        <span
          className={`inline-flex items-center gap-1.5 font-medium rounded-full border border-amber-300 bg-amber-50 text-amber-900 ${
            isSm ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-sm'
          } ${className}`}
          title="Data grounded in public infrastructure registers (e.g. PMGSY / LGD)."
        >
          <Database className={`${isSm ? 'w-3 h-3' : 'w-4 h-4'} text-amber-700`} />
          <span className="font-semibold">Government Source</span>
          {modelOrSource && <span className="text-amber-700/80 text-[10px]">({modelOrSource})</span>}
        </span>
      );

    case 'COMMUNITY_VERIFICATION':
      return (
        <span
          className={`inline-flex items-center gap-1.5 font-medium rounded-full border border-teal-300 bg-teal-50 text-teal-900 ${
            isSm ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-sm'
          } ${className}`}
        >
          <Users className={`${isSm ? 'w-3 h-3' : 'w-4 h-4'} text-teal-700`} />
          <span className="font-semibold">Community Ground Truth</span>
        </span>
      );

    case 'CONTRACTOR_SUBMISSION':
      return (
        <span
          className={`inline-flex items-center gap-1.5 font-medium rounded-full border border-blue-300 bg-blue-50 text-blue-900 ${
            isSm ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-sm'
          } ${className}`}
        >
          <HardHat className={`${isSm ? 'w-3 h-3' : 'w-4 h-4'} text-blue-700`} />
          <span className="font-semibold">Contractor Claim</span>
        </span>
      );

    case 'PROTOTYPE_DATA':
    default:
      return (
        <span
          className={`inline-flex items-center gap-1.5 font-medium rounded-full border border-slate-300 bg-slate-100 text-slate-700 ${
            isSm ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-sm'
          } ${className}`}
          title="Sandbox / prototype demonstration environment."
        >
          <FileText className={`${isSm ? 'w-3 h-3' : 'w-4 h-4'} text-slate-500`} />
          <span className="font-semibold">PROTOTYPE_DATA</span>
        </span>
      );
  }
};
